[project]
name = "gradingassistant"
version = "0.1.0"
description = "Helper for geoweb grading."
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "openpyxl>=3.1.5",
    "pandas>=2.2.3",
]

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"
