"""Export a structured grading excel to HTML"""

#standard
from pathlib import Path
import csv
from typing import Tuple
import math
#external
import pandas as pd
#internal

def parse_grading_sheet(sheet: Path, group: int) -> dict:
    """Parse a structured grading sheet generated by the templator, return dict."""
    output = {"Question":[],
              "Marks Available":[],
              "Mark":[],
              "Feedback":[]
              }
    question_columns: list[int] = []
    marks_available_columns: list[int] = []
    mark_columns: list[int] = []
    feedback_columns: list[int] = []
    with open(sheet, "r") as f:
        reader = csv.reader(f)
        for idx, row in enumerate(reader):
            if idx == 0:
                for id, header in enumerate(row):
                    match header:
                        case "question":
                            question_columns.append(id)
                        case "marks available":
                            marks_available_columns.append(id)
                        case "mark":
                            mark_columns.append(id)
                        case "feedback":
                            feedback_columns.append(id)
            if idx == group:
                for id, data in enumerate(row):
                    if id in question_columns:
                        output["Question"].append(data)
                    elif id in marks_available_columns:
                        output["Marks Available"].append(data)
                    elif id in mark_columns:
                        data.strip()
                        data = 0 if data == '' else data
                        data = int(float(data))
                        output["Mark"].append(int(data))
                    elif id in feedback_columns:
                        output["Feedback"].append(data)
    return output

def convert_to_dataframe(data:dict) -> pd.DataFrame:
    # return on this is not so nice.
    df = pd.DataFrame(data)
    total = df["Mark"].sum()
    totals_row = {"Question": "",
             "Marks Available": "Your Total:",
             "Mark":total,
             "Feedback":""
             }
    df = pd.concat([df, pd.DataFrame([totals_row])], ignore_index=True)
    return df

def combine_dataframes(sheet_1: Path, sheet_2: Path, group: int, labs:list[int]) -> pd.DataFrame:
    """Combine two dataframes and add totals."""
    df_1 = convert_to_dataframe(parse_grading_sheet(sheet_1, group))
    df_1_total = (df_1["Mark"].sum() / 2)
    df_2 = convert_to_dataframe(parse_grading_sheet(sheet_2, group))
    df_2_total = (df_2["Mark"].sum() / 2)
    grade_total = math.ceil(((df_1_total+ df_2_total) / 2)) 
    group_header = {"Question":f"Group {group}",
                   "Marks Available":"",
                   "Mark":"",
                   "Feedback":""} 
    df_1_header = {"Question":f"Lab{labs[0]}",
                   "Marks Available":"",
                   "Mark":"",
                   "Feedback":""}
    df_2_header = {"Question":f"Lab {labs[1]}",
                   "Marks Available":"",
                   "Mark":"",
                   "Feedback":""}
    grand_total = {"Question": "",
             "Marks Available": "Grand Total",
             "Mark":grade_total,
             "Feedback":""
             }
    combined_df = pd.concat(
            [
                pd.DataFrame([group_header]),
                pd.DataFrame([df_1_header]),
                df_1,
                pd.DataFrame([df_2_header]),
                df_2,
                pd.DataFrame([grand_total]),
                ],
            ignore_index = True
    )
    return combined_df


def to_html(combined_df:pd.DataFrame, group: int, assignment: int) -> None:
    html_table = combined_df.to_html(index=False, escape=True, classes="my-table")
    html_content = f"""
    <!DOCTYPE html>
    <html>
    <head>
        <meta charset="UTF-8">
        <title>Styled Table</title>
        <style>
            .my-table {{
                font-family: Arial, sans-serif;
                border-collapse: collapse;
                width: 100%;
            }}
            .my-table th, .my-table td {{
                border: 1px solid #ddd;
                padding: 8px;
            }}
            .my-table tr:nth-child(even) {{
                background-color: #f2f2f2;
            }}
            .my-table th {{
                background-color: #f4f4f4;
            }}
        </style>
    </head>
    <body>
        {html_table}
    </body>
    </html>
    """

    with open(f"feedback-assignment{assignment}-group{group}.html", "w") as f:
        f.write(html_content)

if __name__ == "__main__":
    assignment_no = int(input("What assignment number is this? "))
    group_numbers = int(input("How many groups are there? "))
    sheet_1 = Path(input("Enter path to first grading sheet, must be in a .csv format: ").replace('"', ""))
    sheet_2 = Path(input("Enter path to second grading sheet, must be in a .csv format: ").replace('"', ""))
    for group in range(1, group_numbers+1):
        combined_df = combine_dataframes(sheet_1, sheet_2, group, [1,2])
        to_html(combined_df, group, assignment_no)
        print(f"Group {group} saved to HTML!")
